pull_request_rules:
- actions:
    merge:
      method: squash
      rebase_fallback: merge
  conditions:
  - label!=no-mergify
  - '#approved-reviews-by>=1'
  - 'status-success=ci/circleci: build'
  name: master
