working_directory: &working_directory
  ~/project

defaults: &defaults
  docker:
    - image: circleci/python:3.7.2-stretch-node
  working_directory: *working_directory

repo_cache_key: &repo_cache_key
  deps-{{ checksum "requirements.txt" }}

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: *repo_cache_key
      - run:
          name: Prepare environment
          command: make venv
      - save_cache:
          paths:
            - ./venv
          key: *repo_cache_key
      - persist_to_workspace:
          root: *working_directory
          paths: venv/*
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run:
          name: Build site
          command: make build
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - add_ssh_keys:
          fingerprints:
            - "16:d6:67:78:1b:d1:1b:57:2a:c3:60:1c:92:4b:03:01"
      - run:
          name: Publish site
          command: make publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
